# エイリアスの設定
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'

# プロンプトの設定
PS1='\[\033[01;32m\]\u@docker\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# その他の設定
export LANG=ja_JP.UTF-8
export TERM=xterm-256color
