services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        command: php artisan octane:start --server=frankenphp
        # command: php artisan serve
        ports:
            - "3000:3000"
            - "80:8000"
            - "5173:5173"  # Viteポート
        volumes:
            - ./src:/app
            - ./docker/caddy/data:/data
            - ./docker/caddy/config:/config
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            XDEBUG_MODE: "debug,develop"
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9004 start_with_request=yes"
            PHP_IDE_CONFIG: "serverName=frankenphp"
            VITE_HOST: "localhost"
            VITE_PORT: "5173"
            OCTANE_HOST: "0.0.0.0"
            OCTANE_PORT: "8000"
    mariadb:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/log:/var/log/mysql
    phpmyadmin:
        build:
            context: .
            dockerfile: ./docker/phpmyadmin/Dockerfile
        ports:
            - 8081:80
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        volumes:
            - ./docker/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
            - /sessions
